<?php

/**
 * @file
 * リビジョン確認.
 */

/**
 * Implements hook_theme().
 */
function training_theme($existing, $type, $theme, $path) {
  return [
    'hello_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function training_cron() {
  $type = \Drupal::service('plugin.manager.tapioca');

  // 利用可能なプラグインを取得.
  $plugin_definitions = $type->getDefinitions();

  $plugin_definitions = reset($plugin_definitions);

  \Drupal::messenger()->addStatus($plugin_definitions['id']);

  $plugin = $type->createInstance($plugin_definitions['id'], ['of' => 'configuration values']);

  \Drupal::messenger()->addStatus($plugin->getOrder());
}
